### ISSUE TITLE
The log is always verbose

### ISSUE THREAD

**Issue by maury91** [bitrise-steplib/steps-cache-push#3]
Seems that `Debug mode = false` don't have any effect.
This slows down the build, making the cache totally useless

**Comment by viktorbenei** [comment]
What do you mean by verbose?

> This slows down the build, making the cache totally useless

If possible you should __always__ use an indicator file (e.g. `./Pods -> ./Podfile.lock` - https://discuss.bitrise.io/t/how-to-cache-cocoapods-dependencies/193), which indicates when the cache have to be refreshed. When you don't specify an indicator file, the step have to go through all files meant to be cached and calculate a hash for every file, so that it can properly decide when the cache have to be updated.

**Comment by maury91** [comment]
By verbose I mean that the step generates 200MB of logs.
You can see something like 100000 lines of `(i) File changed:`

The problem is that the step `yarn` changes all the modified times every time, even on modules already installed.

I'm using `node_modules -> yarn.lock`

**Comment by viktorbenei** [comment]
Can you send us a log like that? Or a reproduction repo?

If you have the time also feel free to send us a PR, we'd be glad to review, help and merge it!

**Comment by trapacska** [comment]
This issue is resolved since cache:push v1.0.0. Thank you for reporting the issue, please don't forget to update your step version to the latest. Feel free to re-open this issue if you encounter any issue again.

🚀🎉
